title: "Space Society"
email: your.email@example.com
description: >-
  Official site of the Space Society of [Your College Name]. 
  Explore our projects, missions, and space-related activities!
baseurl: "" 
url: "https://yourusername.github.io"
