title: "Space Exploration Society"
email: ashishdash2410@gmail.com
description: >-
  Official site of the Space Exploration Society ,IIT Bhilai. 
  Explore our projects, missions, and space-related activities!
baseurl: "" 
url: "https://ashish-kumar-dash.github.io"
